#!/bin/bash

export ROOT_PATH=$(dirname $(readlink -f $0))
NULL="> /dev/null 2>&1"

. $ROOT_PATH/bin/setenv.sh

set_smtp(){
  mail_reg="^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"
  server_reg="^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$"
  port_reg="[0-9]{1,5}"
  while true; do
    echo "We need an email account to send the scan report:"
    read email
    email="${email,,}"

    if [[ $email =~ $mail_reg ]]; then
      break
    else
      echo "Invalid email address, please try again"
    fi
  done

  domain=$(echo $email | grep -Eo '[^@]+$')

  server_name=$(awk "/$domain/{print \$2}" $ROOT_PATH/conf/smtp_list.txt)
  port=$(awk "/$domain/{print \$3}" $ROOT_PATH/conf/smtp_list.txt)
  if [ -z $server_name ]; then
    echo "It seems not a common domain, we need the smtp server name of this domain:"
    while true; do
      read server_name
      server_name="${server_name,,}"
      if [[ $server_name =~ $server_reg ]]; then
        break
      else
        echo "Invalid server name, try again please"
      fi
    done
    while true; do
      echo "The smtp port of the server:"
      read port
      if [[ $port =~ $port_reg ]]; then
        break
      else
        echo "Invalid port number, try again please"
      fi
    done
  fi
  while true; do
    echo "The password to login your email:"
    read -s password
    if [ ! -z $password ]; then
      break
    else
      echo "Invalid port number, try again please"
    fi
  done
  username=${email/"@"$domain/""}

  key="SMTP_ADDRESS"
  sed -i "s/\($key *= *\).*/\1$server_name/" $ROOT_PATH/conf/revok.conf

  key="SMTP_PORT"
  sed -i "s/\($key *= *\).*/\1$port/" $ROOT_PATH/conf/revok.conf

  key="SMTP_USER"
  sed -i "s/\($key *= *\).*/\1$username/" $ROOT_PATH/conf/revok.conf

  key="SMTP_PASSWORD"
  sed -i "s/\($key *= *\).*/\1$password/" $ROOT_PATH/conf/revok.conf

  key="EMAIL_ADDRESS"
  sed -i "s/\($key *= *\).*/\1$email/" $ROOT_PATH/conf/revok.conf
}

init() {
  # Pre-init check
  # JRE check
  echo -en "Check JRE installation..."
  which java > /dev/null
  if [ $? == 1 ]; then
    echo "Please install Java Runtime Environment at first"
    exit 1
  fi
  echo "done"

  # Tcl check
  echo -en "Check Tcl installation..."
  which tclsh > /dev/null
  if [ $? == 1 ]; then
    echo "Please install Tcl at first"
    exit 1
  fi
  echo "done"

  # Init SMTP config
  set_smtp

  # Make dirs
  echo -en "Make directories..."
  eval mkdir -p var/lock $NULL
  eval mkdir -p var/run $NULL
  eval mkdir -p var/log $NULL
  echo "done"

  # Softlink bin files
  echo -en "Make softlinks..."
  eval ln -s $PHANTOM_JS_DIR/bin/phantomjs $ROOT_PATH/bin/phantomjs $NULL
  eval ln -s $MITMPROXY_DIR/mitmproxy $ROOT_PATH/bin/mitmproxy $NULL
  eval ln -s $MITMPROXY_DIR/mitmdump $ROOT_PATH/bin/mitmdump $NULL
  eval ln -s $ROOT_PATH/lib/libffi.so.5.0.6 $ROOT_PATH/lib/libffi.so $NULL
  eval ln -s $ROOT_PATH/lib/libffi.so.5.0.6 $ROOT_PATH/lib/libffi.so.5 $NULL
  eval ln -s $ROOT_PATH/lib/libyaml-0.so.2.0.4 $ROOT_PATH/lib/libyaml.so $NULL
  eval ln -s $ROOT_PATH/lib/libyaml-0.so.2.0.4 $ROOT_PATH/lib/libyaml-0.so.2 $NULL
  echo "done"

  # Config iptables
  echo "Configure iptables, may need the password for root..."
  su - -c "iptables -I INPUT 1 -p tcp -m tcp --dport $AMPQ_PORT -j ACCEPT;
  iptables -I INPUT 1 -p tcp -m tcp --dport $DB_PORT -j ACCEPT;
  iptables -I INPUT 1 -p tcp -m tcp --dport $REST_PORT -j ACCEPT;
  iptables -I INPUT 1 -p tcp -m tcp --dport $WEB_PORT -j ACCEPT"
  echo "done"
}

start() {
  $ROOT_PATH/activemq/activemqd start
  $ROOT_PATH/db/postgresql start
  $ROOT_PATH/caroline/carolined start
  $ROOT_PATH/rest/rest-served start
  $ROOT_PATH/webconsole/rackd start
  echo "Now, you can access http://127.0.0.1:3030 in your browser to try Revok, have a nice day"
}

stop() {
  $ROOT_PATH/webconsole/rackd stop
  $ROOT_PATH/rest/rest-served stop
  $ROOT_PATH/caroline/carolined stop
  $ROOT_PATH/db/postgresql stop
  $ROOT_PATH/activemq/activemqd stop
}

status() {
  $ROOT_PATH/activemq/activemqd status
  $ROOT_PATH/rest/rest-served status
  $ROOT_PATH/caroline/carolined status
  $ROOT_PATH/webconsole/rackd status
  $ROOT_PATH/db/postgresql status
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  status)
    status
  ;;
  restart|reload)
    stop
    start
  ;;
  init)
    init
  ;;
  *)
    echo $"Usage: $0 {init|start|stop|status|restart}"
    exit 1
esac
