#!/bin/bash

# Name for the service, used in logging
NAME=postgresql

# Where to write the log file?
SVC_LOG_FILE="$ROOT_PATH/var/log/$NAME.log"

# SERVICE ENTRY POINTS (START/STOP)
# Start Command
restart() {
  echo "Starting $NAME: "
  pg_ctl restart -D $DB_DATA_DIR -s -o "-p ${DB_PORT}" -w -t 300 -m fast -l $SVC_LOG_FILE >> $SVC_LOG_FILE 2>&1
  
  if [ $? -eq 0 ]; then
    echo Done
    return 0
  else
    return 1
  fi
}

stop() {
  echo "Stopping $NAME: "
  pg_ctl stop -D $DB_DATA_DIR -s -m fast -l $SVC_LOG_FILE

  if [ $? -eq 0 ]; then
    echo Done
    return 0
  else
    return 1
  fi
}

status() {
  pg_ctl status -D $DB_DATA_DIR >> $SVC_LOG_FILE 2>&1
  if [ $? -eq 0 ]; then
    echo "$NAME is running"
  else
    echo "$NAME is not running"
  fi
}

case "$1" in
  start)
    restart
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac
